### ISSUE TITLE
Christmas Tweets

### ISSUE THREAD

**Issue by thejeffreystone** [thejeffreystone/home-assistant-configuration#26]
Add in some tweets for the Christmas countdown.

**Comment by CCOSTAN** [comment]
How are you building the days til sensors?   I can see it's a python script but can't really see any of the meat...

**Comment by thejeffreystone** [comment]
Let me fix that. The config file I'm using isn't in the repo because it contains birthdays and upcoming vacations. Something I ' want in the repo as you can imagine. But, I can spin off the Holidays into its own config.

**Comment by CCOSTAN** [comment]
Oh Awesome!  I may have found a better way to do it using Wolfram Alpha and the Rest API.  I'm making a quicky video on it now. :) 

I think the big advantage is it will work with moving holidays such as thanksgiving and easter and doesn't require any updating to account for new years.   I'll post a link here once done.

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/issues/288

**Comment by thejeffreystone** [comment]
https://github.com/thejeffreystone/home-assistant-configuration/blob/master/packages/holidays.yaml

Basic info on how I use in the file.

But may totally steal your API idea.

**Comment by CCOSTAN** [comment]
Ha!  I think I am going to run yours just for anniversaries..  Love that you can say " Mom and Dad have been married for XX years now" ..

**Comment by thejeffreystone** [comment]
Yes! 
I totally need to start doing videos on this stuff...

**Comment by CCOSTAN** [comment]
I always welcome guest vids on my channel (links back to your blog of course) if you don't want to go FULL youtube. :) 
Even if you just share some raw footage, I'd be glad to edit it up and get it published.   Good content is hard to come by. -Carlo

**Comment by thejeffreystone** [comment]
Christmas Tweets primed and ready to go.

https://github.com/thejeffreystone/home-assistant-configuration/commit/cbf2c016337129cab03c39576d0bcf5c7a8205c4
