### ISSUE TITLE
Updated github issue creation with this

### ISSUE THREAD

**Issue by thejeffreystone** [thejeffreystone/home-assistant-configuration#62]
> it's using ifttt because I didn't want to write a python script to do it.

I didn't want to do that either, so fought with the RESTful command integration to make it work for me. Results at https://github.com/kylegordon/home-assistant-config/blob/master/packages/update_notifier.yaml

_Originally posted by @kylegordon in https://github.com/thejeffreystone/home-assistant-configuration/issues/61#issuecomment-620729616_

**Comment by thejeffreystone** [comment]
Boom...lets see if this works...

https://github.com/thejeffreystone/home-assistant-configuration/commit/a06253446b74e3a79d247328f5c3f2c27fcb9f55

**Comment by thejeffreystone** [comment]
Yep. Works. Nice addition @kylegordon

**Comment by BeardedTinker** [comment]
What was the fix in 5da2020 - does token require something else then repo: scope? Fighting this one and can't figure it out.

**Comment by thejeffreystone** [comment]
I dont think so. I think I have to give it everything in Repo though to get it to work. My previous token only had status, deployment and public repo.

But my issue with it definitely was a token scope problem.

J

thejeffreystone | @thejeffreystone | http://jeffreystone.net
